version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_ho_uz
    restart: always
    environment:
      POSTGRES_USER: ho_uz_user
      POSTGRES_PASSWORD: ho_uz_password
      POSTGRES_DB: ho_uz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - external_network
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_ho_uz
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - external_network

networks:
  external_network:
    external: true

volumes:
  postgres_data:
  redis_data:
