# Generated by Django 4.2.13 on 2024-07-05 20:00

from django.db import migrations, models
import django.db.models.deletion
import ho_uz.place.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('size', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='places/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='place.category')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=ho_uz.place.models.get_shot_upload_path)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='place.place')),
            ],
        ),
    ]
